# Generated by Django 4.1.7 on 2023-06-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('theory_tree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('tasks', models.ManyToManyField(related_name='themes', to='tasks.task', verbose_name='Задачи')),
                ('theory_tags', models.ManyToManyField(related_name='themes', to='theory_tree.theorytag', verbose_name='Теги теории')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
    ]
