# Generated by Django 4.1.7 on 2023-06-05 16:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import tasks.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='TaggedContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=120, verbose_name='Название(номер и тд)')),
                ('image', models.ImageField(blank=True, null=True, upload_to=tasks.models.get_task_image_upload_path, verbose_name='Картинка задачи')),
                ('verified', models.BooleanField(default=False, verbose_name='Проверено?')),
                ('script', models.FileField(blank=True, null=True, upload_to=tasks.models.get_task_script_upload_path, verbose_name='Скрипт')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tasks.TaggedContentItem', to='tasks.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': [],
            },
        ),
        migrations.AddField(
            model_name='taggedcontentitem',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taggedcontentitem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.tag'),
        ),
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Номер блока')),
                ('x', models.IntegerField(verbose_name='x')),
                ('y', models.IntegerField(verbose_name='y')),
                ('width', models.IntegerField(verbose_name='width')),
                ('height', models.IntegerField(verbose_name='height')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_blocks', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Блок на картинке задачи',
                'verbose_name_plural': 'Блоки на картинке задачи',
                'ordering': ['task__pk'],
            },
        ),
    ]
