# Generated by Django 4.1.7 on 2023-06-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaggedContentItem',
        ),
    ]
