# Generated by Django 4.1.7 on 2023-06-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_delete_taggedcontentitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
